name: gallary
description: A Flutter app to upload images with notes using local storage.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  path_provider: ^2.0.15
  image_picker: ^1.0.4
  collection: ^1.18.0

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.1.7

flutter:
  uses-material-design: true
